version: '3.8'

services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: project:v1
    container_name: web-container
    ports:
      - "8080:8080"
    restart: unless-stopped
